ristretto = require '../src/ristretto'

task 'build', 'compile sample app', (options) ->
  ristretto.bundle
    target    : 'build.js'
    main      : 'src/app.coffee'
    raw       : ['raw/globals.js']
    minify    : true
    libraries :
      util : 'libraries/util.js'
    copyright : """
      ©2011 Your Name-Here
    """